// Generated by gencpp from file api2python/api_infoRequest.msg
// DO NOT EDIT!


#ifndef API2PYTHON_MESSAGE_API_INFOREQUEST_H
#define API2PYTHON_MESSAGE_API_INFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/Twist.h>
#include <nav_msgs/Path.h>
#include <nav_msgs/OccupancyGrid.h>

namespace api2python
{
template <class ContainerAllocator>
struct api_infoRequest_
{
  typedef api_infoRequest_<ContainerAllocator> Type;

  api_infoRequest_()
    : robot_pose()
    , robot_vel()
    , reference_path()
    , map()  {
    }
  api_infoRequest_(const ContainerAllocator& _alloc)
    : robot_pose(_alloc)
    , robot_vel(_alloc)
    , reference_path(_alloc)
    , map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _robot_pose_type;
  _robot_pose_type robot_pose;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _robot_vel_type;
  _robot_vel_type robot_vel;

   typedef  ::nav_msgs::Path_<ContainerAllocator>  _reference_path_type;
  _reference_path_type reference_path;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _map_type;
  _map_type map;





  typedef boost::shared_ptr< ::api2python::api_infoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api2python::api_infoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct api_infoRequest_

typedef ::api2python::api_infoRequest_<std::allocator<void> > api_infoRequest;

typedef boost::shared_ptr< ::api2python::api_infoRequest > api_infoRequestPtr;
typedef boost::shared_ptr< ::api2python::api_infoRequest const> api_infoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api2python::api_infoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api2python::api_infoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::api2python::api_infoRequest_<ContainerAllocator1> & lhs, const ::api2python::api_infoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_pose == rhs.robot_pose &&
    lhs.robot_vel == rhs.robot_vel &&
    lhs.reference_path == rhs.reference_path &&
    lhs.map == rhs.map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::api2python::api_infoRequest_<ContainerAllocator1> & lhs, const ::api2python::api_infoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace api2python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::api2python::api_infoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api2python::api_infoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api2python::api_infoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api2python::api_infoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api2python::api_infoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api2python::api_infoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api2python::api_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90cbf6a5fd1cabed47e3738002cf6e7d";
  }

  static const char* value(const ::api2python::api_infoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90cbf6a5fd1cabedULL;
  static const uint64_t static_value2 = 0x47e3738002cf6e7dULL;
};

template<class ContainerAllocator>
struct DataType< ::api2python::api_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api2python/api_infoRequest";
  }

  static const char* value(const ::api2python::api_infoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api2python::api_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped robot_pose\n"
"geometry_msgs/Twist robot_vel\n"
"nav_msgs/Path reference_path\n"
"nav_msgs/OccupancyGrid map      #地图\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/OccupancyGrid\n"
"# This represents a 2-D grid map, in which each cell represents the probability of\n"
"# occupancy.\n"
"\n"
"Header header \n"
"\n"
"#MetaData for the map\n"
"MapMetaData info\n"
"\n"
"# The map data, in row-major order, starting with (0,0).  Occupancy\n"
"# probabilities are in the range [0,100].  Unknown is -1.\n"
"int8[] data\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
;
  }

  static const char* value(const ::api2python::api_infoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api2python::api_infoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_pose);
      stream.next(m.robot_vel);
      stream.next(m.reference_path);
      stream.next(m.map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct api_infoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api2python::api_infoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api2python::api_infoRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_pose);
    s << indent << "robot_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_vel);
    s << indent << "reference_path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.reference_path);
    s << indent << "map: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API2PYTHON_MESSAGE_API_INFOREQUEST_H
