// Generated by gencpp from file api2python/api_info.msg
// DO NOT EDIT!


#ifndef API2PYTHON_MESSAGE_API_INFO_H
#define API2PYTHON_MESSAGE_API_INFO_H

#include <ros/service_traits.h>


#include <api2python/api_infoRequest.h>
#include <api2python/api_infoResponse.h>


namespace api2python
{

struct api_info
{

typedef api_infoRequest Request;
typedef api_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct api_info
} // namespace api2python


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api2python::api_info > {
  static const char* value()
  {
    return "2e0aa5b6b51d31843d46fc8ed1324a8c";
  }

  static const char* value(const ::api2python::api_info&) { return value(); }
};

template<>
struct DataType< ::api2python::api_info > {
  static const char* value()
  {
    return "api2python/api_info";
  }

  static const char* value(const ::api2python::api_info&) { return value(); }
};


// service_traits::MD5Sum< ::api2python::api_infoRequest> should match
// service_traits::MD5Sum< ::api2python::api_info >
template<>
struct MD5Sum< ::api2python::api_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api2python::api_info >::value();
  }
  static const char* value(const ::api2python::api_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api2python::api_infoRequest> should match
// service_traits::DataType< ::api2python::api_info >
template<>
struct DataType< ::api2python::api_infoRequest>
{
  static const char* value()
  {
    return DataType< ::api2python::api_info >::value();
  }
  static const char* value(const ::api2python::api_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api2python::api_infoResponse> should match
// service_traits::MD5Sum< ::api2python::api_info >
template<>
struct MD5Sum< ::api2python::api_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api2python::api_info >::value();
  }
  static const char* value(const ::api2python::api_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api2python::api_infoResponse> should match
// service_traits::DataType< ::api2python::api_info >
template<>
struct DataType< ::api2python::api_infoResponse>
{
  static const char* value()
  {
    return DataType< ::api2python::api_info >::value();
  }
  static const char* value(const ::api2python::api_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API2PYTHON_MESSAGE_API_INFO_H
